#Step 1: CA1 Dataset Loading


In [ ]:
!pip install imblearn

In [ ]:
from pandas import read_csv,get_dummies,DataFrame,Series
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
import numpy as np

In [ ]:
data=read_csv("/content/adult_cen_inc.csv")
data

age workclass  fnlwgt     education  education.num      marital.status  \
0       90         ?   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66         ?  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0                      ?  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2                      ?      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

In [ ]:
data['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

'workclass','occupation'

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


#Step 2: Data modification and imputation

In [ ]:
data['workclass'].unique()

array(['?', 'Private', 'State-gov', 'Federal-gov', 'Self-emp-not-inc',
       'Self-emp-inc', 'Local-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

In [ ]:
data['sex'].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
data['sex']=data['sex'].replace({'Male':1,'Female':0})

<ipython-input-8-7eeaf481b936>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['sex']=data['sex'].replace({'Male':1,'Female':0})


In [ ]:
a=data['workclass'].mode()[0];a

'Private'

In [ ]:
data['workclass']= data['workclass'].replace({'?':a})

In [ ]:
data['fnlwgt'].unique() #multi

array([ 77053, 132870, 186061, ...,  34066,  84661, 257302])

In [ ]:
data['occupation'].unique() #multi

array(['?', 'Exec-managerial', 'Machine-op-inspct', 'Prof-specialty',
       'Other-service', 'Adm-clerical', 'Craft-repair',
       'Transport-moving', 'Handlers-cleaners', 'Sales',
       'Farming-fishing', 'Tech-support', 'Protective-serv',
       'Armed-Forces', 'Priv-house-serv'], dtype=object)

In [ ]:
a=data['occupation'].mode()[0];a

'Prof-specialty'

In [ ]:
data['occupation']= data['occupation'].replace({'?':a})

In [ ]:
data['hours.per.week'].unique() #bi

array([40, 18, 45, 20, 60, 35, 55, 76, 50, 42, 25, 32, 90, 48, 15, 70, 52,
       72, 39,  6, 65, 12, 80, 67, 99, 30, 75, 26, 36, 10, 84, 38, 62, 44,
        8, 28, 59,  5, 24, 57, 34, 37, 46, 56, 41, 98, 43, 63,  1, 47, 68,
       54,  2, 16,  9,  3,  4, 33, 23, 22, 64, 51, 19, 58, 53, 96, 66, 21,
        7, 13, 27, 11, 14, 77, 31, 78, 49, 17, 85, 87, 88, 73, 89, 97, 94,
       29, 82, 86, 91, 81, 92, 61, 74, 95])

In [ ]:
a=data['native.country'].mode()[0];a

'United-States'

In [ ]:
data['native.country']= data['native.country'].replace({'?':a})

In [ ]:
data['income'].unique() #bi

array(['<=50K', '>50K'], dtype=object)

In [ ]:
data['income']=data['income'].replace({'<=50K':0,'>50K':1})

<ipython-input-19-b4541e6d6360>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['income']=data['income'].replace({'<=50K':0,'>50K':1})


# Step 3:One-Hot Encoding for Multi-Class Variables:

education,workclass,marital.status,occupation,relationship,race,native.countryeducation,workclass,marital.status,occupation,relationship,race,native.country


In [ ]:
features=['education','workclass','marital.status','occupation','relationship','race','native.country']

In [ ]:
data2=get_dummies(data,features)

In [ ]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Columns: 105 entries, age to native.country_Yugoslavia
dtypes: bool(97), int64(8)
memory usage: 5.0 MB


In [ ]:
data2.shape

(32561, 105)

# Step 4: Selection of Dependent and independent variable.

In [ ]:
y=data2['income']
y #edible 1 or poisonous 2 Dependent variable Y

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    0
32558    1
32559    0
32560    0
Name: income, Length: 32561, dtype: int64

In [ ]:
x=data2.drop('income',axis=1)   #independent Variables X
x

age  fnlwgt  education.num  sex  capital.gain  capital.loss  \
0       90   77053              9    0             0          4356   
1       82  132870              9    0             0          4356   
2       66  186061             10    0             0          4356   
3       54  140359              4    0             0          3900   
4       41  264663             10    0             0          3900   
...    ...     ...            ...  ...           ...           ...   
32556   22  310152             10    1             0             0   
32557   27  257302             12    0             0             0   
32558   40  154374              9    1             0             0   
32559   58  151910              9    0             0             0   
32560   22  201490              9    1             0             0   

       hours.per.week  education_Federal-gov  education_Local-gov  \
0                  40                  False                False   
1                  18                  False                False   
2                  40                  False                False   
3                  40                  False                False   
4                  40                  False                False   
...               ...                    ...                  ...   
32556              40                  False                False   
32557              38                  False                False   
32558              40                  False                False   
32559              40                  False                False   
32560              20                  False                False   

       education_Never-worked  ...  native.country_Portugal  \
0                       False  ...                    False   
1                       False  ...                    False   
2                       False  ...                    False   
3                       False  ...                    False   
4                       False  ...                    False   
...                       ...  ...                      ...   
32556                   False  ...                    False   
32557                   False  ...                    False   
32558                   False  ...                    False   
32559                   False  ...                    False   
32560                   False  ...                    False   

       native.country_Puerto-Rico  native.country_Scotland  \
0                           False                    False   
1                           False                    False   
2                           False                    False   
3                           False                    False   
4                           False                    False   
...                           ...                      ...   
32556                       False                    False   
32557                       False                    False   
32558                       False                    False   
32559                       False                    False   
32560                       False                    False   

       native.country_South  native.country_Taiwan  native.country_Thailand  \
0                     False                  False                    False   
1                     False                  False                    False   
2                     False                  False                    False   
3                     False                  False                    False   
4                     False                  False                    False   
...                     ...                    ...                      ...   
32556                 False                  False                    False   
32557                 False                  False                    False   
32558                 False                  False                    False   
32559                 False                  

#Step 5: Feature Scaling

In [ ]:
x_scaled=StandardScaler().fit_transform(x)
x_scaled

array([[ 3.76961234, -1.06799736, -0.42005962, ...,  0.30720846,
        -0.04540836, -0.02217266],
       [ 3.18311167, -0.53916866, -0.42005962, ...,  0.30720846,
        -0.04540836, -0.02217266],
       [ 2.01011032, -0.03521956, -0.03136003, ...,  0.30720846,
        -0.04540836, -0.02217266],
       ...,
       [ 0.10398314, -0.33543266, -0.42005962, ...,  0.30720846,
        -0.04540836, -0.02217266],
       [ 1.42360965, -0.35877741, -0.42005962, ...,  0.30720846,
        -0.04540836, -0.02217266],
       [-1.21564337,  0.11095988, -0.42005962, ...,  0.30720846,
        -0.04540836, -0.02217266]])

In [ ]:
DataFrame(x_scaled)

0         1         2         3        4          5         6    \
0      3.769612 -1.067997 -0.420060 -1.422331 -0.14592  10.593507 -0.035429   
1      3.183112 -0.539169 -0.420060 -1.422331 -0.14592  10.593507 -1.817204   
2      2.010110 -0.035220 -0.031360 -1.422331 -0.14592  10.593507 -0.035429   
3      1.130359 -0.468215 -2.363558 -1.422331 -0.14592   9.461864 -0.035429   
4      0.177296  0.709482 -0.031360 -1.422331 -0.14592   9.461864 -0.035429   
...         ...       ...       ...       ...      ...        ...       ...   
32556 -1.215643  1.140460 -0.031360  0.703071 -0.14592  -0.216660 -0.035429   
32557 -0.849080  0.639741  0.746039 -1.422331 -0.14592  -0.216660 -0.197409   
32558  0.103983 -0.335433 -0.420060  0.703071 -0.14592  -0.216660 -0.035429   
32559  1.423610 -0.358777 -0.420060 -1.422331 -0.14592  -0.216660 -0.035429   
32560 -1.215643  0.110960 -0.420060  0.703071 -0.14592  -0.216660 -1.655225   

            7         8         9    ...       94        95        96   \
0     -0.174295 -0.262097 -0.014664  ... -0.033729 -0.059274 -0.019201   
1     -0.174295 -0.262097 -0.014664  ... -0.033729 -0.059274 -0.019201   
2     -0.174295 -0.262097 -0.014664  ... -0.033729 -0.059274 -0.019201   
3     -0.174295 -0.262097 -0.014664  ... -0.033729 -0.059274 -0.019201   
4     -0.174295 -0.262097 -0.014664  ... -0.033729 -0.059274 -0.019201   
...         ...       ...       ...  ...       ...       ...       ...   
32556 -0.174295 -0.262097 -0.014664  ... -0.033729 -0.059274 -0.019201   
32557 -0.174295 -0.262097 -0.014664  ... -0.033729 -0.059274 -0.019201   
32558 -0.174295 -0.262097 -0.014664  ... -0.033729 -0.059274 -0.019201   
32559 -0.174295 -0.262097 -0.014664  ... -0.033729 -0.059274 -0.019201   
32560 -0.174295 -0.262097 -0.014664  ... -0.033729 -0.059274 -0.019201   

            97        98        99        100       101       102       103  
0     -0.049628 -0.039607 -0.023518 -0.024163  0.307208 -0.045408 -0.022173  
1     -0.049628 -0.039607 -0.023518 -0.024163  0.307208 -0.045408 -0.022173  
2     -0.049628 -0.039607 -0.023518 -0.024163  0.307208 -0.045408 -0.022173  
3     -0.049628 -0.039607 -0.023518 -0.024163  0.307208 -0.045408 -0.022173  
4     -0.049628 -0.039607 -0.023518 -0.024163  0.307208 -0.045408 -0.022173  
...         ...       ...       ...       ...       ...       ...       ...  
32556 -0.049628 -0.039607 -0.023518 -0.024163  0.307208 -0.045408 -0.022173  
32557 -0.049628 -0.039607 -0.023518 -0.024163  0.307208 -0.045408 -0.022173  
32558 -0.049628 -0.039607 -0.023518 -0.024163  0.307208 -0.045408 -0.022173  
32559 -0.049628 -0.039607 -0.023518 -0.024163  0.307208 -0.045408 -0.022173  
32560 -0.049628 -0.039607 -0.023518 -0.024163  0.307208 -0.045408 -0.022173  

[32561 rows x 104 columns]

#Step 6:Test and train dataset split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size = 0.2, random_state = 100)

In [ ]:
y_train.shape

(26048,)

In [ ]:
x_train.shape

(26048, 104)

In [ ]:
y_train.value_counts()

income
0    19800
1     6248
Name: count, dtype: int64

#Step 7: Handling Class Imbalance with SMOTE

In [ ]:
smote=SMOTE(random_state=1)

In [ ]:
y_train

12303    0
28040    0
11921    0
18797    0
17424    0
        ..
12119    0
24423    0
14147    1
23320    0
5640     0
Name: income, Length: 26048, dtype: int64

In [ ]:
x_train

array([[-1.43558112,  0.41687654, -0.03136003, ...,  0.30720846,
        -0.04540836, -0.02217266],
       [-0.48251753, -0.12114226, -1.58615841, ...,  0.30720846,
        -0.04540836, -0.02217266],
       [ 2.15673549, -1.52099352, -0.42005962, ...,  0.30720846,
        -0.04540836, -0.02217266],
       ...,
       [-0.18926719,  2.02476514,  1.52343836, ...,  0.30720846,
        -0.04540836, -0.02217266],
       [-0.77576787, -0.78473383, -0.42005962, ...,  0.30720846,
        -0.04540836, -0.02217266],
       [-0.11595461,  2.04593079, -3.1409568 , ..., -3.2551187 ,
        -0.04540836, -0.02217266]])

In [ ]:
x_train, y_train =smote.fit_resample(x_train, y_train)


In [ ]:
y_train.value_counts()

income
0    19800
1    19800
Name: count, dtype: int64

In [ ]:
x_train.shape

(39600, 104)

# Step 8: Model training ,optimization and evaluation: Decision Tree

In [ ]:
from sklearn import tree

In [ ]:
dec_tree=tree.DecisionTreeClassifier(criterion='entropy',max_depth=2)#decison tree classifier building and max_depth is pre proning step

In [ ]:
dec_tree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=2)

In [ ]:
y_pred=dec_tree.predict(x_test) # Predicted Y value on the test dataset

In [ ]:
y_pred

array([0, 1, 1, ..., 0, 0, 0])

# Evaluating the performance of the Model: Decision Tree

In [ ]:
from sklearn import metrics

In [ ]:
Accuracy= metrics.accuracy_score(y_test,y_pred) # Calculating the accuracy of the model build
Recall= metrics.recall_score(y_test,y_pred) # Calculating the recall of the model build
Precision= metrics.precision_score(y_test,y_pred) # Calculating the precision of the model build
print('Accuracy:', Accuracy)
print('Recall:', Recall)
print('Precision:', Precision)

Accuracy: 0.7130354675264855
Recall: 0.8625235404896422
Precision: 0.45436507936507936


If accuracy precision and recall is 1.0 or close to one (like 0.934) then model is overfitting
and it need to correct

In [ ]:
conf_mat= metrics.confusion_matrix(y_test,y_pred) # Confusion matrix
conf_mat

array([[3270, 1650],
       [ 219, 1374]])

# optimal parameter on the basis of data by using grid search/ Validation of model


In [ ]:
  from sklearn.model_selection import GridSearchCV

  dec_tree2= tree.DecisionTreeClassifier(criterion='entropy',random_state=1) # Decision Tree Classifier Building

  depth={'max_depth': [2,6,10,12,25,45,87,9,86,28,30,36]} # Grid of max_depth parameter length = 8

  grid_search=GridSearchCV(estimator=dec_tree2,param_grid=depth,scoring='precision',cv=5) # CV is k-fold we give CV-counter validation

  grid_search.fit(x_train,y_train) # Fitting decision tree classifier to the training set
  best_depth= grid_search.best_params_ # Selecting the optimal parameter max_depth
  print(best_depth)


{'max_depth': 87}


In [ ]:
# Refitting the model with the optimal/best max_depth parameter selected based on the precision
dec_tree_best_depth= tree.DecisionTreeClassifier(criterion='entropy',max_depth=87) # Decision Tree Classifier Building
dec_tree_best_depth.fit(x_train,y_train) # Fitting decision tree classifier to the training set
y_pred=dec_tree_best_depth.predict(x_test) # Predicted Y value on the test dataset

If accurcy decreases after validation and refitting the model then it was previously overfitted.

In [ ]:
  from sklearn import metrics
  Accuracy= metrics.accuracy_score(y_test,y_pred) # Calculating the accuracy of the model build
  Recall= metrics.recall_score(y_test,y_pred) # Calculating the recall of the model build
  Precision= metrics.precision_score(y_test,y_pred) # Calculating the precision of the model build
  print('Accuracy:', Accuracy)
  print('Recall:', Recall)
  print('Precision:', Precision)

Accuracy: 0.8132964839551666
Recall: 0.6660389202762084
Precision: 0.6080229226361031


In [ ]:
conf_mat= metrics.confusion_matrix(y_test,y_pred) # Confusion matrix
conf_mat

array([[4236,  684],
       [ 532, 1061]])

#Step 9: Model training ,optimization and evaluation: Random Forest

In [ ]:
from sklearn import ensemble
RF= ensemble.RandomForestClassifier(n_estimators=100,criterion='entropy',max_features=None,random_state=1)
RF.fit(x_train,y_train) # fitting random forest to training data
y_pred=RF.predict(x_test)

In [ ]:
# Evaluating the random forest
from sklearn import metrics
Accuracy= metrics.accuracy_score(y_test,y_pred) # Calculating the accuracy of the model build
Recall= metrics.recall_score(y_test,y_pred) # Calculating the recall of the model build
Precision= metrics.precision_score(y_test,y_pred) # Calculating the precision of the model build
print('Accuracy:', Accuracy)
print('Recall:', Recall)
print('Precision:', Precision)
conf_mat= metrics.confusion_matrix(y_test,y_pred) # Confusion matrix
conf_mat

Accuracy: 0.8420082911100876
Recall: 0.7030759573132455
Precision: 0.6682577565632458


array([[4364,  556],
       [ 473, 1120]])

#Random forest hyperparameter tuning/ Validation of model.

In [ ]:
from sklearn.model_selection import GridSearchCV

# Selecting the optimal n_estimators parameter
RF1=ensemble.RandomForestClassifier(n_estimators=50,criterion='entropy',max_features=None,random_state=1)
ntrees={'n_estimators': [100,150,180,220,250,300,320,330]} # Grid of n_estimators parameter length = 8

grid_search=GridSearchCV(estimator=RF1,param_grid=ntrees,scoring='precision',cv=5)

grid_search.fit(x_train,y_train) # Fitting decision tree classifier to the training set
best_nestimator= grid_search.best_params_ # Selecting the optimal parameter max_depth
print(best_nestimator)

{'n_estimators': 220}


In [ ]:
# Refit the random forest on the optimal n_estimators parameter
RF2=ensemble.RandomForestClassifier(n_estimators=220,criterion='entropy',max_features=None,random_state=1)
RF2.fit(x_train,y_train) # fitting random forest to training data
y_pred=RF2.predict(x_test)

# Evaluating the refitted random forest with the optimal n_estimator parameter
from sklearn import metrics
   # Calculating the accuracy of the model build
Recall= metrics.recall_score(y_test,y_pred) # Calculating the recall of the model build
Precision= metrics.precision_score(y_test,y_pred) # Calculating the precision of the model build
print('Accuracy:', Accuracy)
print('Recall:', Recall)
print('Precision:', Precision)
conf_mat= metrics.confusion_matrix(y_test,y_pred) # Confusion matrix
conf_mat

Accuracy: 0.8420082911100876
Recall: 0.704331450094162
Precision: 0.6607773851590106


array([[4344,  576],
       [ 471, 1122]])

#Step 10: Model training ,optimization and evaluation:Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
log_reg = LogisticRegression(penalty='l2',max_iter=600,solver='saga')
log_reg.fit(x_train, y_train)

LogisticRegression(max_iter=600, solver='saga')

In [ ]:
y_pred = log_reg.predict(x_test)

In [ ]:
# Evaluating the model based on chosen kernel
from sklearn import metrics

Accuracy= metrics.accuracy_score(y_test,y_pred)
Precision=metrics.precision_score(y_test, y_pred)
Recall = metrics.recall_score(y_test,y_pred)
F1= metrics.f1_score(y_test,y_pred)

print('Accuracy:', Accuracy)
print('Precision:', Precision)
print('Recall:', Recall)
print('F1 score:', F1)

Accuracy: 0.8083832335329342
Precision: 0.5738125802310655
Recall: 0.8418079096045198
F1 score: 0.6824427480916031


In [ ]:
conf_mat=metrics.confusion_matrix(y_test,y_pred)
conf_mat

array([[3924,  996],
       [ 252, 1341]])

# Hyperparameter tuning/ Validation of model.

In [ ]:
param_grid = [
    {'penalty':['l1','l2','elasticnet',None],
    'max_iter'  : [50,100,200,500,700,1000,5000,10000],
     'l1_ratio':[0.1]
}
]

In [ ]:
log_reg = LogisticRegression(solver='saga')


In [ ]:
  from sklearn.model_selection import GridSearchCV
LR_grid = GridSearchCV(log_reg ,param_grid = param_grid, cv = 3, verbose=True,n_jobs=-1)

LR_grid.fit(x_train, y_train)

Fitting 3 folds for each of 32 candidates, totalling 96 fits


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(


GridSearchCV(cv=3, estimator=LogisticRegression(solver='saga'), n_jobs=-1,
             param_grid=[{'l1_ratio': [0.1],
                          'max_iter': [50, 100, 200, 500, 700, 1000, 5000,
                                       10000],
                          'penalty': ['l1', 'l2', 'elasticnet', None]}],
             verbose=True)

In [ ]:
LR_grid.best_estimator_

LogisticRegression(l1_ratio=0.1, max_iter=500, penalty=None, solver='saga')

In [ ]:
log_reg=LogisticRegression(l1_ratio=0.1, max_iter=500, penalty=None, solver='saga')

In [ ]:

log_reg.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(


LogisticRegression(l1_ratio=0.1, max_iter=500, penalty=None, solver='saga')

In [ ]:
y_pred = log_reg.predict(x_test)

In [ ]:
# Evaluating the model based on chosen kernel
from sklearn import metrics

Accuracy= metrics.accuracy_score(y_test,y_pred)
Precision=metrics.precision_score(y_test, y_pred)
Recall = metrics.recall_score(y_test,y_pred)
F1= metrics.f1_score(y_test,y_pred)

print('Accuracy:', Accuracy)
print('Precision:', Precision)
print('Recall:', Recall)
print('F1 score:', F1)

conf_mat=metrics.confusion_matrix(y_test,y_pred)
conf_mat

Accuracy: 0.8080761553815446
Precision: 0.5734475374732334
Recall: 0.8405524168236033
F1 score: 0.6817718940936863


array([[3924,  996],
       [ 254, 1339]])